---
title: "Descriptive Analysis"
author: "Mengxiao Luan"
output: pdf_document
---

```{r package}
library(dplyr)
library(survey)
```

```{r setup}
nhanes_subpop_htn = readRDS("./nhanes_subpop_htn.rds")

htndstrat = svydesign(ids = ~ svy_psu, strata = ~ svy_strata, weights = ~ svy_weight_cal, 
                      data = nhanes_subpop_htn, nest = TRUE)

```

```{r descriptive}
age = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_age_cat, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(age, rownames = list(age = c("18-44", "45-64", "65-74", "75+")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)
```

```{r}
race = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_race, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(race, rownames = list(race = c("White", "Black", "Asian", "Hispanic", "Other")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)
```

```{r}
preg_status = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_pregnant, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(preg_status, rownames = list(preg_status = c("No Pregnancy", " Pregnancy")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)
```

```{r}
gender = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_gender, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(gender, rownames = list(gender = c("Men", "Women")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

```

```{r}
smoke = svyby(~ bp_uncontrolled_140_90, ~ interaction(cc_smoke, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(smoke, rownames = list(smoke = c("Never", "Former", "Current")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

```

