---
title: "Integrated Codes of Final Project"
author: "Heming Pei, Mengxiao Luan, Yilei Yang, Yaduo Wang"
output: html_document
---

```{r package}
library(cardioStatsUSA)
library(dplyr)
library(survey)
library(mice)
```

```{r data}
# data input
data_key = nhanes_key

nhanes_data = nhanes_data |> 
  mutate(demo_age_cat = as.factor(demo_age_cat),
         demo_race = as.factor(demo_race),
         demo_race_black = as.factor(demo_race_black),
         demo_gender = as.factor(demo_gender),
         bp_control_140_90 = as.factor(bp_control_140_90),
         bp_med_use = as.factor(bp_med_use),
         cc_smoke = as.factor(cc_smoke),
         cc_bmi = as.factor(cc_bmi),
         svy_year = as.factor(svy_year))

# combine year cycles
nhanes_data = nhanes_data |>
  mutate(svy_weight_mec = svy_weight_mec / 10.6)

# create binary indicator
nhanes_data = nhanes_data |>
  mutate(svy_post2013 = 
           ifelse(svy_year %in% c("2013-2014", "2015-2016", "2017-2020"), "Yes", "No")) |>
  mutate(svy_post2013 = as.factor(svy_post2013))

# subgroup and calibration
nhanes_sub = nhanes_data[svy_subpop_htn == 1]
nhanes_sub = nhanes_calibrate(nhanes_sub, nhanes_data, "svy_year")

# create survey design
htndstrat = svydesign(ids = ~ svy_psu, strata = ~ svy_strata, weights = ~ svy_weight_cal, 
                      data = nhanes_sub, nest = TRUE)
```

```{r descrptive}
# table 1
age = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_age_cat, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(age, rownames = list(age = c("18-44", "45-64", "65-74", "75+")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

race = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_race, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(race, rownames = list(race = c("White", "Black", "Asian", "Hispanic", "Other")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

preg_status = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_pregnant, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(preg_status, rownames = list(preg_status = c("No Pregnancy", " Pregnancy")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

gender = svyby(~ bp_uncontrolled_140_90, ~ interaction(demo_gender, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(gender, rownames = list(gender = c("Men", "Women")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

smoke = svyby(~ bp_uncontrolled_140_90, ~ interaction(cc_smoke, svy_post2013), 
            design = htndstrat, svymean)
print(ftable(smoke, rownames = list(smoke = c("Never", "Former", "Current")), 
       com.imp = c("pre 2013", "post 2013")), digits = 2)

svychisq(~ demo_age_cat + svy_post2013, design = htndstrat, statistic = "F")
svychisq(~ demo_race + svy_post2013, design = htndstrat, statistic = "F")
svychisq(~ demo_pregnant + svy_post2013, design = htndstrat, statistic = "F")
svychisq(~ demo_gender + svy_post2013, design = htndstrat, statistic = "F")
svychisq(~ demo_smoke + svy_post2013, design = htndstrat, statistic = "F")

# figure 1
htn_pre2013 = subset(htndstrat, svy_post2013 == "No")
htn_post2013 = subset(htndstrat, svy_post2013 == "Yes")

par(mfrow = c(1,2))

barplot(svyby(~ bp_uncontrolled_140_90, ~ svy_post2013, htndstrat, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("Before 2013", "After 2013"),
        main = "Proportion of BP Uncontrolled")

barplot(svyby(~ bp_uncontrolled_140_90, ~ svy_post2013, htndstrat, svymean, na.rm = TRUE), 
        beside = TRUE, names.arg = c("Before 2013", "After 2013"),
        main = "Proportion of BP Uncontrolled")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_age_cat, htn_pre2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("18-44", "45-64", "65-74", "75+"), 
        main = "Age Groups before 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_age_cat, htn_post2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("18-44", "45-64", "65-74", "75+"), 
        main = "Age Groups after 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_race, htn_pre2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("White", "Black", "Asian", "Hispanic", "Other"), 
        main = "Race Groups before 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_race, htn_post2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("White", "Black", "Asian", "Hispanic", "Other"), 
        main = "Race Groups after 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_pregnant, htn_pre2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("No Pregnancy", " Pregnancy"), 
        main = "Pregnancy Groups before 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_pregnant, htn_post2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("No Pregnancy", " Pregnancy"), 
        main = "Pregnancy Groups after 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_gender, htn_pre2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("Men", "Women"), 
        main = "Gender Groups before 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ demo_gender, htn_post2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("Men", "Women"), 
        main = "Gender Groups after 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ cc_smoke, htn_pre2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("Never", "Former", "Current"), 
        main = "Smoke Groups before 2013")

barplot(svyby(~ bp_uncontrolled_140_90, ~ cc_smoke, htn_post2013, svymean, na.rm = TRUE), 
        beside = FALSE, names.arg = c("Never", "Former", "Current"), 
        main = "Smoke Groups after 2013")
```

```{r model}
# multiple imputation
data <- nhanes_sub %>% 
  select(svy_year,svy_psu, svy_strata, bp_control_140_90, starts_with("demo_"), 
         bp_med_recommended_escesh, bp_med_n_pills, starts_with("cc_"), 
         svy_post2013,svy_weight_cal,-cc_cvd_chd,-cc_cvd_hf)

method <- mice(data, m = 1, maxit = 0)$method
method
method["cc_egfr"] <- "norm" 
method["cc_acr"] <- "norm" 
method["cc_hba1c"] <- "norm" 

imp <- mice(data, m = 5, method = method, maxit = 5, seed = 123)
imputed_datasets <- complete(imp, "all")

# regression
results <- lapply(imputed_datasets, function(dataset) {
  design = svydesign(ids = ~ svy_psu, strata = ~ svy_strata, weights = ~ svy_weight_cal, 
                      data = dataset, nest = TRUE)
  svyglm(bp_control_140_90 ~ demo_age_cat + demo_race + demo_gender + demo_pregnant + bp_med_recommended_escesh + bp_med_n_pills + cc_smoke + cc_bmi + cc_diabetes + cc_ckd + cc_cvd_any + cc_egfr_lt60 + cc_acr_gteq30 + cc_hba1c + svy_post2013, family = quasibinomial, design = design) 
})

pooled_results <- pool(results)

summary(pooled_results)

# IPTW
results <- lapply(imputed_datasets, function(dataset) {
  
  design = svydesign(ids = ~ svy_psu, strata = ~ svy_strata, weights = ~ svy_weight_cal, 
                      data = dataset, nest = TRUE)

  ps_model <- svyglm(svy_post2013 ~ demo_age_cat + demo_race + demo_gender + demo_pregnant + bp_med_recommended_escesh + bp_med_n_pills + cc_smoke + cc_bmi + cc_diabetes + cc_ckd + cc_cvd_any + cc_egfr_lt60 + cc_acr_gteq30 + cc_hba1c , family = binomial, design = design) 
  
  dataset$ps <- ps_model$fitted.values
  
  dataset$iptw <- ifelse(dataset$svy_post2013=="Yes", 1/dataset$ps,1/(1-dataset$ps))
  
  new_design = svydesign(ids = ~ svy_psu, strata = ~ svy_strata, weights = ~ svy_weight_cal*iptw, 
                      data = dataset, nest = TRUE)
  
  svyglm(bp_control_140_90 ~ svy_post2013, family = binomial, design = new_design) 
})

pooled_results <- pool(results)

summary(pooled_results)
```
